/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_metamusic_trm_TRM */

#ifndef _Included_org_metamusic_trm_TRM
#define _Included_org_metamusic_trm_TRM
#ifdef __cplusplus
extern "C" {
#endif
#undef org_metamusic_trm_TRM_TRM_OK
#define org_metamusic_trm_TRM_TRM_OK 0L
#undef org_metamusic_trm_TRM_TRM_FILENOTFOUND
#define org_metamusic_trm_TRM_TRM_FILENOTFOUND -1L
#undef org_metamusic_trm_TRM_TRM_DECODEERR
#define org_metamusic_trm_TRM_TRM_DECODEERR -2L
#undef org_metamusic_trm_TRM_TRM_CANNOTCONNECT
#define org_metamusic_trm_TRM_TRM_CANNOTCONNECT -3L
#undef org_metamusic_trm_TRM_TRM_OTHERERROR
#define org_metamusic_trm_TRM_TRM_OTHERERROR -4L
/*
 * Class:     org_metamusic_trm_TRM
 * Method:    generateTRMforMP3
 * Signature: (Ljava/lang/String;JLjava/lang/String;ILorg/metamusic/trm/TRM/TRMStruct;)I
 */
JNIEXPORT jint JNICALL Java_org_metamusic_trm_TRM_generateTRMforMP3
  (JNIEnv *, jclass, jstring, jlong, jstring, jint, jobject);

/*
 * Class:     org_metamusic_trm_TRM
 * Method:    generateTRMforWAV
 * Signature: (Ljava/lang/String;JLjava/lang/String;ILorg/metamusic/trm/TRM/TRMStruct;)I
 */
JNIEXPORT jint JNICALL Java_org_metamusic_trm_TRM_generateTRMforWAV
  (JNIEnv *, jclass, jstring, jlong, jstring, jint, jobject);

/*
 * Class:     org_metamusic_trm_TRM
 * Method:    generateTRMforOggVorbis
 * Signature: (Ljava/lang/String;JLjava/lang/String;ILorg/metamusic/trm/TRM/TRMStruct;)I
 */
JNIEXPORT jint JNICALL Java_org_metamusic_trm_TRM_generateTRMforOggVorbis
  (JNIEnv *, jclass, jstring, jlong, jstring, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
