/*
  You may freely copy, distribute, modify and use this class as long
  as the original author attribution remains intact.  See message
  below.

  Copyright (C) 2003 Christian Pesch. All Rights Reserved.
 */

package slash.metamusic.mp3.sections;

/**
 * Defines the type of languages in TLAN, COMM, USLT frames.
 *
 * @author Christian Pesch
 * @version $Id: ISO639Type.java 801 2006-04-30 16:00:45Z cpesch $
 */

public class ISO639Type {
    public static final ISO639Type[] ISO639_TYPES = {
            new ISO639Type("Abkhazian", "abk"),
            new ISO639Type("Achinese", "ace"),
            new ISO639Type("Acoli", "ach"),
            new ISO639Type("Adangme", "ada"),
            new ISO639Type("Afar", "aar"),
            new ISO639Type("Afrihili", "afh"),
            new ISO639Type("Afrikaans", "afr"),
            new ISO639Type("Afro-Asiatic (Other)", "afa"),
            new ISO639Type("Akan", "aka"),
            new ISO639Type("Akkadian", "akk"),
            new ISO639Type("Albanian", "alb"),
            new ISO639Type("Aleut", "ale"),
            new ISO639Type("Algonquian languages", "alg"),
            new ISO639Type("Altaic (Other)", "tut"),
            new ISO639Type("Amharic", "amh"),
            new ISO639Type("Apache languages", "apa"),
            new ISO639Type("Arabic", "ara"),
            new ISO639Type("Aramaic", "arc"),
            new ISO639Type("Arapaho", "arp"),
            new ISO639Type("Araucanian", "arn"),
            new ISO639Type("Arawak", "arw"),
            new ISO639Type("Armenian", "arm"),
            new ISO639Type("Artificial (Other)", "art"),
            new ISO639Type("Assamese, asmAsturian", "ast"),
            new ISO639Type("Athapascan languages", "ath"),
            new ISO639Type("Australian languages", "aus"),
            new ISO639Type("Austronesian (Other)", "map"),
            new ISO639Type("Avaric", "ava"),
            new ISO639Type("Avestan", "ave"),
            new ISO639Type("Awadhi", "awa"),
            new ISO639Type("Aymara", "aym"),
            new ISO639Type("Azerbaijani", "aze"),
            new ISO639Type("Bable", "ast"),
            new ISO639Type("Balinese", "ban"),
            new ISO639Type("Baltic (Other)", "bat"),
            new ISO639Type("Baluchi", "bal"),
            new ISO639Type("Bambara", "bam"),
            new ISO639Type("Bamileke languages", "bai"),
            new ISO639Type("Banda", "bad"),
            new ISO639Type("Bantu (Other)", "bnt"),
            new ISO639Type("Basa", "bas"),
            new ISO639Type("Bashkir", "bak"),
            new ISO639Type("Basque", "baq"),
            new ISO639Type("Batak (Indonesia)", "btk"),
            new ISO639Type("Beja", "bej"),
            new ISO639Type("Belarusian", "bel"),
            new ISO639Type("Bemba", "bem"),
            new ISO639Type("Bengali", "ben"),
            new ISO639Type("Berber (Other)", "ber"),
            new ISO639Type("Bhojpuri", "bho"),
            new ISO639Type("Bihari", "bih"),
            new ISO639Type("Bikol", "bik"),
            new ISO639Type("Bini", "bin"),
            new ISO639Type("Bislama", "bis"),
            new ISO639Type("Bokmål, Norwegian", "nob"),
            new ISO639Type("Bosnian", "bos"),
            new ISO639Type("Braj", "bra"),
            new ISO639Type("Breton", "bre"),
            new ISO639Type("Buginese", "bug"),
            new ISO639Type("Bulgarian", "bul"),
            new ISO639Type("Buriat", "bua"),
            new ISO639Type("Burmese", "bur"),
            new ISO639Type("Caddo", "cad"),
            new ISO639Type("Carib", "car"),
            new ISO639Type("Castilian", "spa"),
            new ISO639Type("Catalan", "cat"),
            new ISO639Type("Caucasian (Other)", "cau"),
            new ISO639Type("Cebuano", "ceb"),
            new ISO639Type("Celtic (Other)", "cel"),
            new ISO639Type("Central American Indian (Other)", "cai"),
            new ISO639Type("Chagatai", "chg"),
            new ISO639Type("Chamic languages", "cmc"),
            new ISO639Type("Chamorro", "cha"),
            new ISO639Type("Chechen", "che"),
            new ISO639Type("Cherokee", "chr"),
            new ISO639Type("Chewa", "nya"),
            new ISO639Type("Cheyenne", "chy"),
            new ISO639Type("Chibcha", "chb"),
            new ISO639Type("Chichewa", "nya"),
            new ISO639Type("Chinese", "chi"),
            new ISO639Type("Chinook jargon", "chn"),
            new ISO639Type("Chipewyan", "chp"),
            new ISO639Type("Choctaw", "cho"),
            new ISO639Type("Chuang", "zha"),
            new ISO639Type("Church Slavic", "chu"),
            new ISO639Type("Church Slavonic", "chu"),
            new ISO639Type("Chuukese", "chk"),
            new ISO639Type("Chuvash", "chv"),
            new ISO639Type("Coptic", "cop"),
            new ISO639Type("Cornish", "cor"),
            new ISO639Type("Corsican", "cos"),
            new ISO639Type("Cree", "cre"),
            new ISO639Type("Creek", "mus"),
            new ISO639Type("Creoles and pidgins(Other)", "crp"),
            new ISO639Type("Creoles and pidgins, English-based (Other)", "cpe"),
            new ISO639Type("Creoles and pidgins, French-based (Other)", "cpf"),
            new ISO639Type("Creoles and pidgins, Portuguese-based (Other)", "cpp"),
            new ISO639Type("Croatian", "scr"),
            new ISO639Type("Cushitic (Other)", "cus"),
            new ISO639Type("Czech", "cze"),
            new ISO639Type("Dakota", "dak"),
            new ISO639Type("Danish", "dan"),
            new ISO639Type("Dayak", "day"),
            new ISO639Type("Delaware", "del"),
            new ISO639Type("Dinka", "din"),
            new ISO639Type("Divehi", "div"),
            new ISO639Type("Dogri", "doi"),
            new ISO639Type("Dogrib", "dgr"),
            new ISO639Type("Dravidian (Other)", "dra"),
            new ISO639Type("Duala", "dua"),
            new ISO639Type("Dutch", "dut"),
            new ISO639Type("Dutch, Middle (ca. 1050-1350)", "dum"),
            new ISO639Type("Dyula", "dyu"),
            new ISO639Type("Dzongkha", "dzo"),
            new ISO639Type("Efik", "efi"),
            new ISO639Type("Egyptian (Ancient)", "egy"),
            new ISO639Type("Ekajuk", "eka"),
            new ISO639Type("Elamite", "elx"),
            new ISO639Type("English", "eng"),
            new ISO639Type("English, Middle (1100-1500)", "enm"),
            new ISO639Type("English, Old (ca.450-1100)", "ang"),
            new ISO639Type("Esperanto", "epo"),
            new ISO639Type("Estonian", "est"),
            new ISO639Type("Ewe", "ewe"),
            new ISO639Type("Ewondo", "ewo"),
            new ISO639Type("Fang", "fan"),
            new ISO639Type("Fanti", "fat"),
            new ISO639Type("Faroese", "fao"),
            new ISO639Type("Fijian", "fij"),
            new ISO639Type("Finnish", "fin"),
            new ISO639Type("Finno-Ugrian (Other)", "fiu"),
            new ISO639Type("Fon", "fon"),
            new ISO639Type("French", "fre"),
            new ISO639Type("French, Middle (ca.1400-1600)", "frm"),
            new ISO639Type("French, Old (842-ca.1400)", "fro"),
            new ISO639Type("Frisian", "fry"),
            new ISO639Type("Friulian", "fur"),
            new ISO639Type("Fulah", "ful"),
            new ISO639Type("Ga", "gaa"),
            new ISO639Type("Gaelic", "gla"),
            new ISO639Type("Gallegan", "glg"),
            new ISO639Type("Ganda", "lug"),
            new ISO639Type("Gayo", "gay"),
            new ISO639Type("Gbaya", "gba"),
            new ISO639Type("Geez", "gez"),
            new ISO639Type("Georgian", "geo"),
            new ISO639Type("German", "ger"),
            new ISO639Type("German, Low", "nds"),
            new ISO639Type("German, Middle High (ca.1050-1500)", "gmh"),
            new ISO639Type("German, Old High (ca.750-1050)", "goh"),
            new ISO639Type("Germanic (Other)", "gem"),
            new ISO639Type("Gikuyu", "kik"),
            new ISO639Type("Gilbertese", "gil"),
            new ISO639Type("Gondi", "gon"),
            new ISO639Type("Gorontalo", "gor"),
            new ISO639Type("Gothic", "got"),
            new ISO639Type("Grebo", "grb"),
            new ISO639Type("Greek, Ancient (to 1453)", "grc"),
            new ISO639Type("Greek, Modern (1453-)", "gre"),
            new ISO639Type("Guarani", "grn"),
            new ISO639Type("Gujarati", "guj"),
            new ISO639Type("Gwich'in", "gwi"),
            new ISO639Type("Haida", "hai"),
            new ISO639Type("Hausa", "hau"),
            new ISO639Type("Hawaiian", "haw"),
            new ISO639Type("Hebrew", "heb"),
            new ISO639Type("Herero", "her"),
            new ISO639Type("Hiligaynon", "hil"),
            new ISO639Type("Himachali", "him"),
            new ISO639Type("Hindi", "hin"),
            new ISO639Type("Hiri Motu", "hmo"),
            new ISO639Type("Hittite", "hit"),
            new ISO639Type("Hmong", "hmn"),
            new ISO639Type("Hungarian", "hun"),
            new ISO639Type("Hupa", "hup"),
            new ISO639Type("Iban", "iba"),
            new ISO639Type("Icelandic", "ice"),
            new ISO639Type("Ido", "ido"),
            new ISO639Type("Igbo", "ibo"),
            new ISO639Type("Ijo", "ijo"),
            new ISO639Type("Iloko", "ilo"),
            new ISO639Type("Inari Sami", "smn"),
            new ISO639Type("Indic (Other)", "inc"),
            new ISO639Type("Indo-European (Other)", "ine"),
            new ISO639Type("Indonesian", "ind"),
            new ISO639Type("Interlingua (IALA)", "ina"),
            new ISO639Type("Interlingue", "ile"),
            new ISO639Type("Inuktitut", "iku"),
            new ISO639Type("Inupiaq", "ipk"),
            new ISO639Type("Iranian (Other)", "ira"),
            new ISO639Type("Irish", "gle"),
            new ISO639Type("Irish, Middle (900-1200)", "mga"),
            new ISO639Type("Irish, Old (to 900)", "sga"),
            new ISO639Type("Iroquoian languages", "iro"),
            new ISO639Type("Italian", "ita"),
            new ISO639Type("Japanese", "jpn"),
            new ISO639Type("Javanese", "jav"),
            new ISO639Type("Judeo-Arabic", "jrb"),
            new ISO639Type("Judeo-Persian", "jpr"),
            new ISO639Type("Kabyle", "kab"),
            new ISO639Type("Kachin", "kac"),
            new ISO639Type("Kalaallisut", "kal"),
            new ISO639Type("Kamba", "kam"),
            new ISO639Type("Kannada", "kan"),
            new ISO639Type("Kanuri", "kau"),
            new ISO639Type("Kara-Kalpak", "kaa"),
            new ISO639Type("Karen", "kar"),
            new ISO639Type("Kashmiri", "kas"),
            new ISO639Type("Kawi", "kaw"),
            new ISO639Type("Kazakh", "kaz"),
            new ISO639Type("Khasi", "kha"),
            new ISO639Type("Khmer", "khm"),
            new ISO639Type("Khoisan (Other)", "khi"),
            new ISO639Type("Khotanese", "kho"),
            new ISO639Type("Kikuyu", "kik"),
            new ISO639Type("Kimbundu", "kmb"),
            new ISO639Type("Kinyarwanda", "kin"),
            new ISO639Type("Kirghiz", "kir"),
            new ISO639Type("Komi", "kom"),
            new ISO639Type("Kongo", "kon"),
            new ISO639Type("Konkani", "kok"),
            new ISO639Type("Korean", "kor"),
            new ISO639Type("Kosraean", "kos"),
            new ISO639Type("Kpelle", "kpe"),
            new ISO639Type("Kru", "kro"),
            new ISO639Type("Kuanyama", "kua"),
            new ISO639Type("Kumyk", "kum"),
            new ISO639Type("Kurdish", "kur"),
            new ISO639Type("Kurukh", "kru"),
            new ISO639Type("Kutenai", "kut"),
            new ISO639Type("Kwanyama", "kua"),
            new ISO639Type("Ladino", "lad"),
            new ISO639Type("Lahnda", "lah"),
            new ISO639Type("Lamba", "lam"),
            new ISO639Type("Lao", "lao"),
            new ISO639Type("Latin", "lat"),
            new ISO639Type("Latvian", "lav"),
            new ISO639Type("Letzeburgesch", "ltz"),
            new ISO639Type("Lezghian, lezLimburgan, limlimburgish", "lim"),
            new ISO639Type("Lingala", "lin"),
            new ISO639Type("Lithuanian", "lit"),
            new ISO639Type("Low German", "nds"),
            new ISO639Type("Low Saxon", "nds"),
            new ISO639Type("Lozi", "loz"),
            new ISO639Type("Luba-Katanga", "lub"),
            new ISO639Type("Luba-Lulua", "lua"),
            new ISO639Type("Luiseno", "lui"),
            new ISO639Type("Lule Sami", "smj"),
            new ISO639Type("Lunda", "lun"),
            new ISO639Type("Luo (Kenya and Tanzania)", "luo"),
            new ISO639Type("Luxembourgish", "ltz"),
            new ISO639Type("Lushai", "lus"),
            new ISO639Type("Macedonian", "mac"),
            new ISO639Type("Madurese", "mad"),
            new ISO639Type("Magahi", "mag"),
            new ISO639Type("Maithili", "mai"),
            new ISO639Type("Makasar", "mak"),
            new ISO639Type("Malagasy", "mlg"),
            new ISO639Type("Malay", "may"),
            new ISO639Type("Malayalam", "mal"),
            new ISO639Type("Maltese", "mlt"),
            new ISO639Type("Manchu", "mnc"),
            new ISO639Type("Mandar", "mdr"),
            new ISO639Type("Mandingo", "man"),
            new ISO639Type("Manipuri", "mni"),
            new ISO639Type("Manobo languages", "mno"),
            new ISO639Type("Manx", "glv"),
            new ISO639Type("Maori", "mao"),
            new ISO639Type("Marathi", "mar"),
            new ISO639Type("Mari", "chm"),
            new ISO639Type("Marshallese", "mah"),
            new ISO639Type("Marwari", "mwr"),
            new ISO639Type("Masai", "mas"),
            new ISO639Type("Mayan languages", "myn"),
            new ISO639Type("Mende", "men"),
            new ISO639Type("Micmac", "mic"),
            new ISO639Type("Minangkabau", "min"),
            new ISO639Type("Miscellaneous languages", "mis"),
            new ISO639Type("Mohawk", "moh"),
            new ISO639Type("Moldavian", "mol"),
            new ISO639Type("Mon-Khmer (Other)", "mkh"),
            new ISO639Type("Mongo", "lol"),
            new ISO639Type("Mongolian", "mon"),
            new ISO639Type("Mossi", "mos"),
            new ISO639Type("Multiple languages", "mul"),
            new ISO639Type("Munda languages", "mun"),
            new ISO639Type("Nahuatl", "nah"),
            new ISO639Type("Nauru", "nau"),
            new ISO639Type("Navaho", "nav"),
            new ISO639Type("Navajo", "nav"),
            new ISO639Type("Ndebele, North", "nde"),
            new ISO639Type("Ndebele, South", "nbl"),
            new ISO639Type("Ndonga", "ndo"),
            new ISO639Type("Neapolitan", "nap"),
            new ISO639Type("Nepali", "nep"),
            new ISO639Type("Newari", "new"),
            new ISO639Type("Nias", "nia"),
            new ISO639Type("Niger-Kordofanian (Other)", "nic"),
            new ISO639Type("Nilo-Saharan (Other)", "ssa"),
            new ISO639Type("Niuean", "niu"),
            new ISO639Type("Norse, Old", "non"),
            new ISO639Type("North American Indian (Other)", "nai"),
            new ISO639Type("Northern Sami", "sme"),
            new ISO639Type("North Ndebele", "nde"),
            new ISO639Type("Norwegian", "nor"),
            new ISO639Type("Norwegian Bokmål", "nob"),
            new ISO639Type("Norwegian Nynorsk", "nno"),
            new ISO639Type("Nubian languages", "nub"),
            new ISO639Type("Nyamwezi", "nym"),
            new ISO639Type("Nyanja", "nya"),
            new ISO639Type("Nyankole", "nyn"),
            new ISO639Type("Nynorsk, Norwegian", "nno"),
            new ISO639Type("Nyoro", "nyo"),
            new ISO639Type("Nzima", "nzi"),
            new ISO639Type("Occitan (post 1500)", "oci"),
            new ISO639Type("Ojibwa", "oji"),
            new ISO639Type("Old Bulgarian", "chu"),
            new ISO639Type("Old Church Slavonic", "chu"),
            new ISO639Type("Old Slavonic", "chu"),
            new ISO639Type("Oriya", "ori"),
            new ISO639Type("Oromo", "orm"),
            new ISO639Type("Osage", "osa"),
            new ISO639Type("Ossetian", "oss"),
            new ISO639Type("Ossetic", "oss"),
            new ISO639Type("Otomian languages", "oto"),
            new ISO639Type("Pahlavi", "pal"),
            new ISO639Type("Palauan", "pau"),
            new ISO639Type("Pali", "pli"),
            new ISO639Type("Pampanga", "pam"),
            new ISO639Type("Pangasinan", "pag"),
            new ISO639Type("Panjabi", "pan"),
            new ISO639Type("Papiamento", "pap"),
            new ISO639Type("Papuan (Other)", "paa"),
            new ISO639Type("Persian", "per"),
            new ISO639Type("Persian, Old (ca.600-400)", "peo"),
            new ISO639Type("Philippine (Other)", "phi"),
            new ISO639Type("Phoenician", "phn"),
            new ISO639Type("Pohnpeian", "pon"),
            new ISO639Type("Polish", "pol"),
            new ISO639Type("Portuguese", "por"),
            new ISO639Type("Prakrit languages", "pra"),
            new ISO639Type("Provençal", "oci"),
            new ISO639Type("Provençal, Old (to 1500)", "pro"),
            new ISO639Type("Pushto", "pus"),
            new ISO639Type("Quechua", "que"),
            new ISO639Type("Raeto-Romance", "roh"),
            new ISO639Type("Rajasthani", "raj"),
            new ISO639Type("Rapanui", "rap"),
            new ISO639Type("Rarotongan", "rar"),
            new ISO639Type("Reserved for local user", "qaa-qtz"),
            new ISO639Type("Romance (Other)", "roa"),
            new ISO639Type("Romanian", "rum"),
            new ISO639Type("Romany", "rom"),
            new ISO639Type("Rundi", "run"),
            new ISO639Type("Russian", "rus"),
            new ISO639Type("Salishan languages", "sal"),
            new ISO639Type("Samaritan Aramaic", "sam"),
            new ISO639Type("Sami languages (Other)", "smi"),
            new ISO639Type("Samoan", "smo"),
            new ISO639Type("Sandawe", "sad"),
            new ISO639Type("Sango", "sag"),
            new ISO639Type("Sanskrit", "san"),
            new ISO639Type("Santali", "sat"),
            new ISO639Type("Sardinian", "srd"),
            new ISO639Type("Sasak", "sas"),
            new ISO639Type("Saxon, Low", "nds"),
            new ISO639Type("Scots", "sco"),
            new ISO639Type("Scottish Gaelic", "gla"),
            new ISO639Type("Selkup", "sel"),
            new ISO639Type("Semitic (Other)", "sem"),
            new ISO639Type("Serbian", "scc"),
            new ISO639Type("Serer", "srr"),
            new ISO639Type("Shan", "shn"),
            new ISO639Type("Shona", "sna"),
            new ISO639Type("Sidamo", "sid"),
            new ISO639Type("Sign languages", "sgn"),
            new ISO639Type("Siksika", "bla"),
            new ISO639Type("Sindhi", "snd"),
            new ISO639Type("Sinhalese", "sin"),
            new ISO639Type("Sino-Tibetan (Other)", "sit"),
            new ISO639Type("Siouan languages", "sio"),
            new ISO639Type("Skolt Sami", "sms"),
            new ISO639Type("Slave (Athapascan)", "den"),
            new ISO639Type("Slavic (Other)", "sla"),
            new ISO639Type("Slovak", "slo"),
            new ISO639Type("Slovenian", "slv"),
            new ISO639Type("Sogdian", "sog"),
            new ISO639Type("Somali", "som"),
            new ISO639Type("Songhai", "son"),
            new ISO639Type("Soninke", "snk"),
            new ISO639Type("Sorbian languages", "wen"),
            new ISO639Type("Sotho, Northern", "nso"),
            new ISO639Type("Sotho, Southern", "sot"),
            new ISO639Type("South American Indian (Other)", "sai"),
            new ISO639Type("Southern Sami", "sma"),
            new ISO639Type("South Ndebele", "nbl"),
            new ISO639Type("Spanish", "spa"),
            new ISO639Type("Sukuma", "suk"),
            new ISO639Type("Sumerian", "sux"),
            new ISO639Type("Sundanese", "sun"),
            new ISO639Type("Susu", "sus"),
            new ISO639Type("Swahili", "swa"),
            new ISO639Type("Swati", "ssw"),
            new ISO639Type("Swedish", "swe"),
            new ISO639Type("Syriac", "syr"),
            new ISO639Type("Tagalog", "tgl"),
            new ISO639Type("Tahitian", "tah"),
            new ISO639Type("Tai (Other)", "tai"),
            new ISO639Type("Tajik", "tgk"),
            new ISO639Type("Tamashek", "tmh"),
            new ISO639Type("Tamil", "tam"),
            new ISO639Type("Tatar", "tat"),
            new ISO639Type("Telugu", "tel"),
            new ISO639Type("Tereno", "ter"),
            new ISO639Type("Tetum", "tet"),
            new ISO639Type("Thai", "tha"),
            new ISO639Type("Tibetan", "tib"),
            new ISO639Type("Tigre", "tig"),
            new ISO639Type("Tigrinya", "tir"),
            new ISO639Type("Timne", "tem"),
            new ISO639Type("Tiv", "tiv"),
            new ISO639Type("Tlingit", "tli"),
            new ISO639Type("Tok Pisin", "tpi"),
            new ISO639Type("Tokelau", "tkl"),
            new ISO639Type("Tonga (Nyasa)", "tog"),
            new ISO639Type("Tonga (Tonga Islands)", "ton"),
            new ISO639Type("Tsimshian", "tsi"),
            new ISO639Type("Tsonga", "tso"),
            new ISO639Type("Tswana", "tsn"),
            new ISO639Type("Tumbuka", "tum"),
            new ISO639Type("Tupi languages", "tup"),
            new ISO639Type("Turkish", "tur"),
            new ISO639Type("Turkish, Ottoman (1500-1928)", "ota"),
            new ISO639Type("Turkmen", "tuk"),
            new ISO639Type("Tuvalu", "tvl"),
            new ISO639Type("Tuvinian", "tyv"),
            new ISO639Type("Twi", "twi"),
            new ISO639Type("Ugaritic", "uga"),
            new ISO639Type("Uighur", "uig"),
            new ISO639Type("Ukrainian", "ukr"),
            new ISO639Type("Umbundu", "umb"),
            new ISO639Type("Undetermined", "und"),
            new ISO639Type("Urdu", "urd"),
            new ISO639Type("Uzbek", "uzb"),
            new ISO639Type("Vai", "vai"),
            new ISO639Type("Venda", "ven"),
            new ISO639Type("Vietnamese", "vie"),
            new ISO639Type("Volapük", "vol"),
            new ISO639Type("Votic", "vot"),
            new ISO639Type("Wakashan languages", "wak"),
            new ISO639Type("Walamo", "wal"),
            new ISO639Type("Walloon", "wln"),
            new ISO639Type("Waray", "war"),
            new ISO639Type("Washo", "was"),
            new ISO639Type("Welsh", "wel"),
            new ISO639Type("Wolof", "wol"),
            new ISO639Type("Xhosa", "xho"),
            new ISO639Type("Yakut", "sah"),
            new ISO639Type("Yao", "yao"),
            new ISO639Type("Yapese", "yap"),
            new ISO639Type("Yiddish", "yid"),
            new ISO639Type("Yoruba", "yor"),
            new ISO639Type("Yupik languages", "ypk"),
            new ISO639Type("Zande", "znd"),
            new ISO639Type("Zapotec", "zap"),
            new ISO639Type("Zenaga", "zen"),
            new ISO639Type("Zhuang", "zha"),
            new ISO639Type("Zulu", "zul"),
            new ISO639Type("Zuni", "zun")
    };

    public static boolean isKnownISO639Type(String iso639Code) {
        return getISO639Type(iso639Code) != null;
    }

    public static ISO639Type getISO639Type(String iso639Code) {
        String code = iso639Code.toLowerCase();
        for (ISO639Type iso639Type : ISO639_TYPES) {
            if (iso639Type.getCode().equals(code))
                return iso639Type;
        }
        return null;
    }

    public static boolean isKnownISO639Language(String language) {
        return getISO639Language(language) != null;
    }

    public static ISO639Type getISO639Language(String language) {
        for (ISO639Type iso639Type : ISO639_TYPES) {
            if (iso639Type.getLanguage().equals(language))
                return iso639Type;
        }
        return null;
    }

    private ISO639Type(String language, String code) {
        this.language = language;
        this.code = code;
    }

    public String getCode() {
        return code;
    }

    public String getLanguage() {
        return language;
    }

    private String code;
    private String language;

    public String toString() {
        return "ISO639Type[code=" + getCode() + ", type=" + getLanguage() + "]";
    }
}
