/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* libid3 support */
#define HAVE_LIBID3 1

/* Define to 1 if you have the `mad' library (-lmad). */
#define HAVE_LIBMAD 1

/* Define to 1 if you have the `musicbrainz' library (-lmusicbrainz). */
#define HAVE_LIBMUSICBRAINZ 1

/* Ogg/Vorbis Support */
#define HAVE_OGGVORBIS 1

/* Name of package */
#define PACKAGE "trm"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* "PREFIX" */
#define PREFIX "/usr/local"

/* Version number of package */
#define VERSION "0.2.1"
