//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.12.16 at 11:08:45 PM CET 
//

@XmlSchema package slash.metamusic.itunes.xml.binding;

import javax.xml.bind.annotation.XmlSchema;
