//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.12.16 at 11:08:45 PM CET
//


package slash.metamusic.itunes.xml.binding;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for array element declaration.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;element name="array">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *           &lt;choice>
 *             &lt;element ref="{http://www.w3.org/namespace/}array"/>
 *             &lt;element ref="{http://www.w3.org/namespace/}data"/>
 *             &lt;element ref="{http://www.w3.org/namespace/}date"/>
 *             &lt;element ref="{http://www.w3.org/namespace/}dict"/>
 *             &lt;element ref="{http://www.w3.org/namespace/}real"/>
 *             &lt;element ref="{http://www.w3.org/namespace/}integer"/>
 *             &lt;element ref="{http://www.w3.org/namespace/}string"/>
 *             &lt;element ref="{http://www.w3.org/namespace/}true"/>
 *             &lt;element ref="{http://www.w3.org/namespace/}false"/>
 *           &lt;/choice>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "arrayOrDataOrDate"
})
@XmlRootElement(name = "array")
public class Array {

    @XmlElementRefs({
            @XmlElementRef(name = "real", type = JAXBElement.class),
            @XmlElementRef(name = "false", type = JAXBElement.class),
            @XmlElementRef(name = "dict", type = Dict.class),
            @XmlElementRef(name = "string", type = JAXBElement.class),
            @XmlElementRef(name = "array", type = Array.class),
            @XmlElementRef(name = "date", type = JAXBElement.class),
            @XmlElementRef(name = "data", type = JAXBElement.class),
            @XmlElementRef(name = "true", type = JAXBElement.class),
            @XmlElementRef(name = "integer", type = JAXBElement.class)
    })
    protected List<Object> arrayOrDataOrDate;

    /**
     * Gets the value of the arrayOrDataOrDate property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the arrayOrDataOrDate property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArrayOrDataOrDate().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link Dict }
     * {@link Array }
     * {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    public List<Object> getArrayOrDataOrDate() {
        if (arrayOrDataOrDate == null) {
            arrayOrDataOrDate = new ArrayList<Object>();
        }
        return this.arrayOrDataOrDate;
    }

}
