/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_metamusic_discid_DiscId */

#ifndef _Included_org_metamusic_discid_DiscId
#define _Included_org_metamusic_discid_DiscId
#ifdef __cplusplus
extern "C" {
#endif
#undef org_metamusic_discid_DiscId_FRAMES_PER_SECOND
#define org_metamusic_discid_DiscId_FRAMES_PER_SECOND 75L
/*
 * Class:     org_metamusic_discid_DiscId
 * Method:    deviceRead
 * Signature: (Ljava/lang/String;[I)I
 */
JNIEXPORT jint JNICALL Java_org_metamusic_discid_DiscId_deviceRead
  (JNIEnv *, jclass, jstring, jintArray);

#ifdef __cplusplus
}
#endif
#endif
